34/38, some edge cases

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -5,49 +5,41 @@ function help(){
 	
 
 	echo " script usage:"
-	echo " xtf [FILTER] [COMMAND] [USER_NAME] [LOG]"
+	echo " ./xtf [FILTER] [COMMAND] [USER_NAME] [LOG]"$'\n'"----------------------------------------"
+	echo " [FILTER] -->    after certain date '-a  <YYYY-MM-DD HH:MM:SS>'"
+	echo "          -->   before certain date '-b' <YYYY-MM-DD HH:MM:SS>'"
+	echo "          -->  only lines with currency '-c <code of currency>'"
+
+	echo "----------------------------------------"
+	echo " [COMMAND] -> 'list'/<blank> displays all logs of a trader "
+	echo "           -> 'list-currency' displays currencies that were traded by a trader"
+	echo "           -> 'status' displays status of currencies after all transaction "
+	echo "           -> 'profit' displays status of currencies after certain profit"
+	echo "----------------------------------------"
 	
+	exit 0
+ 
 }
 
 function list(){
 		
-	if [[ "$2" == *.gz ]]; then
-		zgrep "$1" "$2"
-	else
-		grep "$1" "$2"
-	fi
-	
+	echo "$2" | grep "$1"
+
 }
 
 
 
 
 
-function lcurrency(){
+function listcurrency(){
 	
 	all_curr=()
+	while IFS= read -r line; do
+		curr=$(echo "$line" | awk -F';' '{ print $3 }')
+		all_curr+=("$curr")
+	done < <(list "$1" "$2")
 	
-
-	if [[ "$2" == *.gz ]]; then
-
-		for line in "$(zgrep "$1" "$2")"; do
-		
-			curr=$(echo "$line" | cut -d';' -f3)
-			all_curr+=("$curr")
-
-		done
-	else
-	
-		for line in "$(grep "$1" "$2")"; do
-		
-			curr=$(echo "$line" | cut -d';' -f3)
-			all_curr+=("$curr")
-
-		done
-	fi
-
-	echo "${all_curr[@]}" | sort -u
-
+	printf "%s\n" "${all_curr[@]}" | sort -u 
 }
 
 function profit(){
@@ -56,18 +48,17 @@ function profit(){
 		XTF_PROFIT=20
 	fi
 
-	mapfile -t stats < <(status "$1" logs.txt)
+	mapfile -t stats < <(status "$1" "$2")
 
 	for p in "${stats[@]}"; do
 		num=$(echo "$p" | cut -d' ' -f3)
 		curr=$(echo "$p" | cut -d' ' -f1)
 		
 		
-		p=$(echo "0.$XTF_PROFIT")
+		pr=$(echo "scale=2; $XTF_PROFIT / 100" | bc)
 
-			
 		if (( $(echo "$num > 0" | bc -l) )); then
-			num=$(awk -v num="$num" -v p="$p" 'BEGIN { result = num + num * p; printf "%.4f", result }')
+			num=$(awk -v num="$num" -v pr="$pr" 'BEGIN { result = num + num * pr; printf "%.4f", result }')
 			echo "$curr : $num"
 		else 
 			echo "$curr : $num"	
@@ -81,33 +72,14 @@ function status(){
 	all_curr=()
 	all_stats=()
 
+	while IFS= read -r line; do
 
-	if [[ "$2" == *.gz ]]; then
+		curr=$(echo "$line" | cut -d';' -f3)
+		stat=$(echo "$line" | cut -d';' -f3,4)
 		
-		
-		while IFS= read -r line; do
-
-			curr=$(echo "$line" | cut -d';' -f3)
-			stat=$(echo "$line" | cut -d';' -f3,4)
-		
-			all_curr+=("$curr")
-			all_stats+=("$stat")
-
-		done <<< "$(zgrep "$1" "$2")"
-	
-
-	else 
-
-		while IFS= read -r line; do
-
-			curr=$(echo "$line" | cut -d';' -f3)
-			stat=$(echo "$line" | cut -d';' -f3,4)
-		
-			all_curr+=("$curr")
-			all_stats+=("$stat")
-
-		done <<< "$(grep "$1" "$2")"
-	fi
+		all_curr+=("$curr")
+		all_stats+=("$stat")
+	done < <(echo "$2" | grep "$1")
 
 
 	all_stats=($(for element in "${all_stats[@]}"; do echo "$element"; done | sort))
@@ -132,7 +104,7 @@ function status(){
 			((j++))
 		done
 		
-		if [ "$i" == $(echo "${#all_stats[@]}-1" | bc) ]; then
+		if [ "$i" == "$(echo "${#all_stats[@]}-1" | bc)" ]; then
 			results+="$c1 : $num1"
 		else
 			results+="$c1 : "$num1""$'\n'
@@ -161,7 +133,7 @@ function after(){
 		if [[ "$cmp_date" -gt "$date" ]]; then
 			echo "$line"
 		fi				
-	done < <(list "$2" "$3")
+	done < <(echo "$2")
 }
 
 function before(){
@@ -176,7 +148,7 @@ function before(){
 		if [[ "$cmp_date" -lt "$date" ]]; then
 			echo "$line"
 		fi				
-	done < <(list "$2" "$3")
+	done < <(echo "$2")
 
 }
 	
@@ -190,7 +162,7 @@ function currency(){
 		if [[ "$curr" == "$1" ]]; then
 			echo "$line"
 		fi				
-	done < <(list "$2" "$3")
+	done < <(echo "$2")
 
 }
 
@@ -202,134 +174,121 @@ if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
 	fi
 fi
 
-src=0
-name=0
+
+is_file=0
+is_name=0
+is_filter=0
+is_cmd=0
+is_curr=0
+
 for arg in "$@"; do
-
-	if [[ "$arg" == *.log ]]; then	
-		src=1
-		cat "$arg" > logs.txt
-
-	elif [[ "$arg" == *.gz ]]; then
-		src=1
-		zcat "$arg" > logs.txt
+		
+	if [ "$arg" == "status" ] || [ "$arg" == "profit" ] || [ "$arg" == "list" ]; then
+		cmd="$arg"
+		((is_cmd++))
+	elif [ "$arg" == "list-currency" ]; then
+		cmd="listcurrency"
+		((is_cmd++))
 	
-	elif [[ "$arg" =~ ^.{4,}$ ]]; then
-		name=1
+	elif [[ "$arg" == *.gz ]] && [[ "$is_file" == 0 ]]; then	
+		file+=$(zcat "$arg")
+		is_file=1
+	elif [[ "$arg" == *.gz ]] && [[ "$is_file" == 1 ]]; then
+		file+=$'\n'$(zcat "$arg")
+
+	elif [[ "$arg" == *.log ]] && [[ "$is_file" == 0 ]]; then
+		file+=$(cat "$arg")
+		is_file=1	
+	elif [[ "$arg" == *.log ]] && [[ "$is_file" == 1 ]]; then
+		file+=$'\n'$(cat "$arg")
+
+	elif [[ "$arg" =~ ^[[:alnum:]_]{4,}$ ]]; then
+		((is_name++))
+		name="$arg"
 	fi
 done
 
-if [[ "$src" == 0 ]] || [[ "$name" == 0 ]]; then
-	echo "Error: missing one or more crucial arguments." >&2
+index=0
+filters=()
+filters_attr=()
+
+for arg in "$@"; do
+
+	if [[ "$arg" =~ ^-a|-b$ ]]; then
+		filters[$index]="$arg"
+		i="$index"
+		((is_filter++))
+		((index++))
+
+	elif [[ "$arg" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}[[:space:]][0-9]{2}:[0-9]{2}:[0-9]{2}$ ]] && [[ "$i" == "$(($index - 1))" ]]; then
+		is_date=1
+		filters_attr[$((index - 1))]="$arg"
+
+
+	elif [[ "$arg" == "-c" ]]; then
+		filters[$index]="$arg"
+		i="$index"
+		((is_filter++))
+		((index++))
+
+	elif [[ "$arg" =~ ^[A-Z]{2,}$ ]] && [[ "$i" == "$(($index - 1))" ]]; then
+		is_curr=1
+		filters_attr[$((index - 1))]="$arg"
+	
+	fi	
+done
+
+
+if [[ "$is_file" == 0 ]] || [[ "$is_name" != 1 ]] || [[ "$is_cmd" -gt 1 ]]; then
+	echo "ERROR: invalid number of key arguments" >&2
+	exit 1
 fi
 
-if [ $# == 2 ]; then
+#echo "${filters[1]} ${filters_attr[1]}"
+#after "${filters_attr[0]}" "$file"
+#exit 0
 
-	list "$1" logs.txt
-fi
+if [[ "$is_cmd" == 1 ]]; then
 
+	if [[ "$is_filter" -ge 1 ]]; then
+		index=0
+		for f in "${filters[@]}"; do
 
-if [ $# == 3 ]; then
-
-	if [ "$1" == "list" ]; then
-	
-		list "$2" logs.txt 
+			if [ "$f" == "-a" ]; then			
+				file=$(after "${filters_attr[$index]}" "$file")
+			elif [ "$f" == "-b" ]; then
+				file=$(before "${filters_attr[$index]}" "$file")
+			elif [ "$f" == "-c" ]; then
+				file=$(currency "${filters_attr[$index]}" "$file")
+			fi
+			((index++))
+		done
+		"$cmd" "$name" "$file"
+	else 
+		"$cmd" "$name" "$file"	
 	fi
 
+elif [[ "$is_cmd" == 0 ]]; then
 
-	if [ "$1" == "list-currency" ]; then
-	
-		lcurrency "$2" logs.txt
-	fi
+	if [[ "$is_filter" -ge 1 ]]; then
 
-	if [ "$1" == "status" ]; then
-
-		status "$2" logs.txt
-
-	fi
-
-	if [ "$1" == "profit" ]; then
-	
-		profit "$2" logs.txt
-	fi
-fi
-
-if [ $# == 4 ]; then
-	
-	if [ "$1" == "-a" ];then
-		after "$2" "$3" logs.txt
-	fi
-
-	if [ "$1" == "-b" ]; then
-		
-		before "$2" "$3" logs.txt
-		
-	fi
-
-	if [ "$1" == "-c" ]; then
-
-		currency "$2" "$3" logs.txt
-	fi
-
-elif [ $# == 5 ]; then
-	
-	if [ "$1" == "-a" ]; then
-
-
-		if [ "$3" == "list" ]; then
-			after "$2" "$4" logs.txt
-		fi
-
-		if [ "$3" == "list-currency" ]; then
-
-			after "$2" "$4" logs.txt > tmp.txt
-			lcurrency "$4" tmp.txt
-		fi
-
-		if [ "$3" == "status" ]; then
-
-			after "$2" "$4" logs.txt > tmp.txt
-			status "$4" tmp.txt
-		fi
-
-		if [ "$3" == "profit" ]; then
+		index=0
+		for f in "${filters[@]}"; do
 			
-			after "$2" "$4" logs.txt > tmp.txt
-			profit "$4" tmp.txt
-		fi
-
-		rm tmp.txt
-
+			if [ "$f" == "-a" ]; then			
+				file=$(after "${filters_attr[$index]}" "$file")
+			elif [ "$f" == "-b" ]; then
+				file=$(before "${filters_attr[$index]}" "$file")
+			elif [ "$f" == "-c" ]; then
+				file=$(currency "${filters_attr[$index]}" "$file")
+			fi
+			((index++))
+		done
+		list "$name" "$file"
+	else
+		list "$name" "$file"
 	fi
-		
-	if [ "$1" == "-b" ]; then
-
-		if [ "$3" == "list" ]; then
-			before "$2" "$4" logs.txt
-		
-
-		elif [ "$3" == "list-currency" ]; then
-
-			before "$2" "$4" logs.txt > tmp.txt
-			lcurrency "$4" tmp.txt
-			
-		
-		elif [ "$3" == "status" ]; then
-
-			before "$2" "$4" logs.txt > tmp.txt
-			status "$4" tmp.txt
-		
-		elif [ "$3" == "profit" ]; then
-			
-			before "$2" "$4" logs.txt > tmp.txt
-			profit "$4" tmp.txt
-		fi
-		
-		rm tmp.txt
-	fi
-
-
-fi
+fi	
 
 
 
